#!/bin/sh -e

#patch -p1 < 3545.patch
patch -p1 < 3085.patch

mkdir -p build
cd build

../configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-sanitizers

make                                               
make DESTDIR="$1" install                           
